### ISSUE TITLE
Realm_RealmFlag does not have a public method allowing simple construction

### ISSUE THREAD

**Issue by bigglesss** [gtker/wow_messages#44]
As far as I can tell, there's no way to directly construct a `Realm_RealmFlag` from a u8 and `Realm_RealmFlag_SpecifyBuild`. This means that converting previously stored realm flags (from the DB) into the correct struct types for sending to the client requires manually checking the mask and constructing the `Realm_RealmFlag` struct bit by bit using the builder methods.

I think that either `inner` and `specify_build` should be public, or there should be a `.new(inner: u8, specify_build: Realm_RealmFlag_SpecifyBuild) -> Self` function.

I imagine this is probably an issue for subtypes on other messages as well?

**Comment by gtker** [comment]
Fixed in bae3504c6e03236b6e69906fd7b88261dccea208
