### ISSUE TITLE
WOTLK: SMSG_MOTD is incorrect

### ISSUE THREAD

**Issue by MeFisto94** [gtker/wow_messages#79]
When I try to read the MOTD of an AzerothCore 3.3.5a Server, I only get the first letter of the MOTD Message.

This is, because the MOTD apparently is not one `SizedCString` but a sized array of nul-terminated (at least in my observings) strings:
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Motd/ServerMotd.cpp#L37
Mangos TBC seems to have a matching implementation:
https://github.com/cmangos/mangos-tbc/blob/49deff938c4652417de120cef23452c3fd5df03b/src/game/Server/WorldSession.cpp#L837

Trinity claims it's "new in 2.0.1", so may affect TBC as well.

**Comment by gtker** [comment]
Thanks for the excellent issue. You appear to be completely correct. I'll push a fix.

If you could provide a `wowm` test case either through [the built in function](https://github.com/gtker/wow_messages/blob/4396e362fba3c14c6aa378523e347d230d40d09d/wow_world_messages/src/world/shared/smsg_motd_tbc_wrath.rs#L44) or just the bytes that made a correct message it would fill out the test suite as well as the auto generated documentation.

**Comment by MeFisto94** [comment]
Test case here, but keep in mind this was before your patch, thus with my naming differs a bit:
```rust
test SMSG_MOTD {
        nbOfLines = 2;
        motd = [
    "Welcome to an AzerothCore server.", "|cffFF4A2DThis server runs on AzerothCore|r |cff3CE7FFwww.azerothcore.org|r",     ];
    } [
        0x00, 0x74, /* size */
        0x3D, 0x03, /* opcode */
        0x02, 0x00, 0x00, 0x00, /* nbOfLines */
        /* motd: CString[nbOfLines] start */
        0x57, 0x65, 0x6C, 0x63, 0x6F, 0x6D, 0x65, 0x20, 0x74, 0x6F, 0x20, 0x61, 0x6E, 0x20, 0x41, 0x7A, 0x65, 0x72, 0x6F, 0x74, 0x68, 0x43, 0x6F, 0x72, 0x65, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2E, 0x00, /* motd 0 */
        0x7C, 0x63, 0x66, 0x66, 0x46, 0x46, 0x34, 0x41, 0x32, 0x44, 0x54, 0x68, 0x69, 0x73, 0x20, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x20, 0x72, 0x75, 0x6E, 0x73, 0x20, 0x6F, 0x6E, 0x20, 0x41, 0x7A, 0x65, 0x72, 0x6F, 0x74, 0x68, 0x43, 0x6F, 0x72, 0x65, 0x7C, 0x72, 0x20, 0x7C, 0x63, 0x66, 0x66, 0x33, 0x43, 0x45, 0x37, 0x46, 0x46, 0x77, 0x77, 0x77, 0x2E, 0x61, 0x7A, 0x65, 0x72, 0x6F, 0x74, 0x68, 0x63, 0x6F, 0x72, 0x65, 0x2E, 0x6F, 0x72, 0x67, 0x7C, 0x72, 0x00, /* motd 1 */
        /* motd: CString[nbOfLines] end */
    ] {
        versions = "2.4.3 3";
    }
```
