### ISSUE TITLE
`read_sized_c_string_to_vec` can cause a out of memory crash

### ISSUE THREAD

**Issue by kerhong** [gtker/wow_messages#82]
https://github.com/gtker/wow_messages/blob/22842fa515be36cc2426d6df8702e611be35c671/wow_world_messages/src/util/functions/base.rs#L19-L31

`size` is user provided u32, it can cause allocation of 4GB of memory.

Possible fixes:
- ignore size initially and verify it after reading `CString`
- use `size.min(some_reasonable_max_size)`
    - max size can never be greater than
        ```rust
        0x7f_ff_ff // max size in header
        - 2 // min opcode size in header
        - 4 // sized string's length
        ```
    - I think even 0x7fffff is too big of a default, it's still 8MB

from #77

**Comment by gtker** [comment]
I think initially restricting it to `0X7FFFFF` would be fine.

Going even further than this, there are probably plenty of other places where malicious packages could create allocations of way to large a size.

Every array of a variable size could in theory allocate `u32::MAX * object_size` bytes.
It might make sense to have a general `AllocationTooLargeError` for things like this.
