### ISSUE TITLE
Confusing `tag_all versions` overlapping individual item `versions`

### ISSUE THREAD

**Issue by kerhong** [gtker/wow_messages#85]
For example https://github.com/gtker/wow_messages/blob/22842fa515be36cc2426d6df8702e611be35c671/wow_message_parser/wowm/world/spell/cmsg_cancel_cast.wowm has `#tag_all versions "1 2 3";` and the tests have `versions = "1.12";`. This is confusing (and undocumented).

from #77

**Comment by kerhong** [comment]
From https://github.com/gtker/wow_messages/issues/77#issuecomment-1742912225 by @gtker 
> I think I'm currently of the opinion that tests should be marked only with the exact version that they were tested with.

I think having `tag_all versions` overwritten by `versions` would be confusing (as adding tags seems additive in general), but not sure how to make it clearer.

**Comment by gtker** [comment]
Having distinct versions that overlap should probably just be an error, since it's most likely unintended.
