### ISSUE TITLE
`SMSG_ACCOUNT_DATA_TIMES` for 3.3.5 should not have `u32[-]`

### ISSUE THREAD

**Issue by kerhong** [gtker/wow_messages#86]
https://github.com/gtker/wow_messages/blob/22842fa515be36cc2426d6df8702e611be35c671/wow_message_parser/wowm/world/login_logout/smsg_account_data_times.wowm#L50-L52

The comment states "For every bit that is 1 in the mask, write one u32 with the time", so it should really be `u32[mask.count_ones()]`, I don't think wowm currently supports such array length description, but maybe should be added?

**Comment by gtker** [comment]
The mask-and-read pattern is also already used for `PackedGuid`, `UpdateMask`, and some of the other Wrath only types.

It would probably be best to make this a custom type as well, since it avoids complicating the codegen for downstream implementers.
