### ISSUE TITLE
Arrays without comma separation

### ISSUE THREAD

**Issue by kerhong** [gtker/wow_messages#89]
There is only one place in .wowm (as far as I can see) where array doesn't use comma separation

https://github.com/gtker/wow_messages/blob/5f8c6a5c4e340a5882c2fef85ecb012fe380897b/wow_message_parser/wowm/world/queries/smsg_pet_name_query_response.wowm#L17-L18

The comma is listed as optional in https://github.com/gtker/wow_messages/blob/main/wow_message_parser/src/auth.pest#L91

I would propose that:
- this array gets a comma, did that in #88
- pest grammar is updated to force commas, it should be a backwards compatible change as comma was already optional before

**Comment by gtker** [comment]
Good catch.

This is a bug from me wanting to allow trailing commas, but accidentally allowing no commas at all. Oops.

I'm a little swamped right now but I'll get on this when I have time again.
