### ISSUE TITLE
3.3.5a MovementBlock docs are inaccurate

### ISSUE THREAD

**Issue by Kangaroux** [gtker/wow_messages#93]
[3.3.5a MovementBlock](https://gtker.com/wow_messages/docs/movementblock.html#client-version-335)

The "body" section incorrectly lists the following fields as part of `ALWAYS_ALLOW_PITCHING` and `SPLINE_ELEVATION`. They should be listed under `LIVING`:
- fall time
- walk speed
- run speed
- reverse speed
- swim speed
- swim reverse speed
- flight speed
- flight reverse speed
- turn speed
- pitch rate

This is correctly listed in the `.wowm` snippet but incorrectly described below that.

**Comment by gtker** [comment]
Thanks for the report.

This seems to be because the generated Body section handles nested content very poorly since it doesn't print when scopes close again.

Do you have any suggestions for what the text should look like to better convey how the message actually is?

**Comment by Kangaroux** [comment]
> Thanks for the report.
> 
> This seems to be because the generated Body section handles nested content very poorly since it doesn't print when scopes close again.
> 
> Do you have any suggestions for what the text should look like to better convey how the message actually is?

Honestly I think just not having the tables under the code block would be best, if generated data is problematic. I don't know of a good way to represent it, because there's weird cases like `fall_time` that are in between blocks.

**Comment by gtker** [comment]
Sorry for the delay. Containers with nested if statements now don't show the textual description of the layout. Removing the text in order to prevent confusion is probably the best solution.
